name: Build / MyVideo Importer

on:
  push:
    # On Push to Master branch
    branches: 
      - master
    # Ignore all Tags / Release
    tags-ignore:
      - '**'

  workflow_call:
    inputs:
      retention-build:
        description: "Retention Period for Setup files. Default is 90"
        default: 90
        required: false
        type: number

jobs:
  build:
    name: MyVideo Importer Build

    runs-on: windows-2019
    
    steps:
    - name: Setup Visual Studio 2019
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: 16.11

    - name: Git Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        build_git.bat < nul
      working-directory: ${{ github.workspace }}\scripts
      shell: cmd

    - name: Upload Artifact / Plugin
      uses: actions/upload-artifact@v4
      if: ${{ success() }}
      with:
        name: MyVideoImporter
        path: |
          ${{ github.workspace }}\MyVideoImporter\bin\Release\MyVideoImporter.dll
        retention-days: ${{ inputs.retention-build || 90 }}
        if-no-files-found: error
