name: Build / MyVideo Importer

on:
  push:
    # On Push to Master branch
    branches: 
      - master
    # Ignore all Tags / Release
    tags-ignore:
      - '**'

  workflow_call:
    inputs:
      retention-build:
        description: "Retention Period for Setup files. Default is 90"
        default: 90
        required: false
        type: number

jobs:
  build:
    name: MyVideo Importer / Build
    runs-on: windows-2019
    steps:
      - name: Setup Visual Studio 2019
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 16.11

      - name: Create cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}
          key: plugin
          
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: |
          build_git.bat < nul
        working-directory: ${{ github.workspace }}\scripts
        shell: cmd

      - name: Upload Artifact / Plugin
        uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: MyVideoImporter
          path: |
            ${{ github.workspace }}\MyVideoImporter\bin\Release\MyVideoImporter.dll
          retention-days: ${{ inputs.retention-build || 90 }}
          if-no-files-found: error

  codeql:
    name: CodeQL
    uses: ./.github/workflows/codeql.yml
    needs: 
      - build
    permissions:
      security-events: write

  mpe:
    name: MyVideo Importer / MPE
    runs-on: windows-2019
    needs:
      - build
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}
          key: plugin

      - name: Git Checkout / MPE
        uses: actions/checkout@v4
        with:
          repository: andrewjswan/MPE
          path: MPE

      - name: MP folder for MPEMaker
        run: |
          mkdir "C:\Team MediaPortal"
        shell: cmd

      - name: Link to MPEMaker
        run: |
          mklink /J "C:\Team MediaPortal\MediaPortal" "${{ github.workspace }}\MPE\MPEMaker"
        shell: cmd

      - name: Clear Build folder
        run: |
          del /F /Q *.*
        working-directory: ${{ github.workspace }}\builds
        shell: cmd

      - name: Get MPE1 Version
        id: version
        run: |
          ECHO @ECHO OFF > version.cmd
          ECHO FOR /F "tokens=1-3" %%i IN ('Tools\sigcheck.exe -accepteula -q "..\MyVideoImporter\bin\Release\MyVideoImporter.dll"') DO ( IF "%%i %%j"=="File version:" SET version=%%k ) >> version.cmd
          ECHO SET version=%version:~0,-1% >> version.cmd
          ECHO ECHO %version% >> version.cmd
          version.cmd
          version.cmd >> $GITHUB_OUTPUT
        working-directory: ${{ github.workspace }}\scripts
        shell: cmd

      - name: Build MPE1
        run: |
          Create_Installer.bat
        working-directory: ${{ github.workspace }}\scripts
        shell: cmd

      - name: Upload Artifact / MPE1
        uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: MyVideoImporter MPE1
          path: |
            ${{ github.workspace }}\builds\MyVideoImporter-*.mpe1
          retention-days: ${{ inputs.retention-build || 90 }}
          if-no-files-found: error

  ci-status:
    name: Status
    runs-on: ubuntu-latest
    needs:
      - build
      - codeql
      - mpe
    if: always()
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
