name: Release / MyVideo Importer

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: MyVideo Importer Build
    uses: ./.github/workflows/build.yml
  
  release:
    name: Release MyVideo Importer
    needs: build
    permissions:
      contents: write
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: MyVideoImporter MPE1
          path: release-files

      - name: Check Artifacts
        run: |
          ls -l
        working-directory: release-files

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: MyVideo Importer v${{needs.build.outputs.version}}
          tag_name: v${{needs.build.outputs.version}}
          generate_release_notes: true
          files: |
            release-files/*.mpe1

  ci-status:
    name: Status
    runs-on: ubuntu-latest
    needs:
      - build
      - release
    if: always()
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
